version: "3"
services:
    php:
        image: php:8-fpm
        volumes:
            - ./src/:/var/www/html/src/
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
    nginx:
        image: nginx:latest
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src/:/var/www/html/src/
    mysql:
        build: 
            context: ./
            dockerfile: ./docker/mysql/Dockerfile
        volumes:
            - example_lemp_data_store:/var/lib/mysql
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment:
          PMA_HOST: mysql
        ports:
          - "8080:80"

volumes:
    example_lemp_data_store: